// services/report_service.js
import { supabase } from 'boot/supabase.js'
import { renderReportCharts } from '/services/report_charts'
import { useUserStore } from 'src/stores/user.js'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

function addPageFooter(doc, pageNumber, totalPages, dateRange, user, filters = {}) {
  const pageHeight = doc.internal.pageSize.getHeight()
  const pageWidth = doc.internal.pageSize.getWidth()

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(6)
  doc.setTextColor(40)

  // File details on bottom left
  const now = new Date()
  const timestamp = now.toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    timeZone: 'Asia/Manila',
  })

  let yOffset = pageHeight - 14
  doc.text(`PRESERV3D Usage Report (${dateRange})`, 15, yOffset)
  yOffset += 3

  // Add filter information if any filters are applied
  if (filters.userType || filters.college || filters.department) {
    const filterParts = []
    if (filters.userType) filterParts.push(`User Type: ${filters.userType}`)
    if (filters.college) filterParts.push(`College: ${filters.college}`)
    if (filters.department) filterParts.push(`Department: ${filters.department}`)
    doc.text(`Filters: ${filterParts.join(' | ')}`, 15, yOffset)
    yOffset += 3
  }

  doc.text(`Generated by: ${user}`, 15, yOffset)
  yOffset += 3
  doc.text(`Generated on: ${timestamp}`, 15, yOffset)

  // Page number on bottom right
  doc.setFontSize(8)
  doc.setTextColor(1)
  doc.text(`Page ${pageNumber} of ${totalPages}`, pageWidth - 15, pageHeight - 10, {
    align: 'right',
  })
}

export async function generateMonthlyReport({
  startMonth,
  startDay,
  startYear,
  endMonth,
  endDay,
  endYear,
  userType = null,
  college = null,
  department = null,
}) {
  const userStore = useUserStore()
  const user = `${userStore.profile?.first_name || ''} ${userStore.profile?.last_name || ''}`.trim()

  const monthNames = Array.from({ length: 12 }, (_, i) =>
    new Date(2000, i).toLocaleString('default', { month: 'long' }),
  )

  // Date Range Setup
  const startDate = new Date(startYear, startMonth - 1, startDay, 0, 0, 0).toISOString()
  const endDate = new Date(endYear, endMonth - 1, endDay, 23, 59, 59).toISOString()

  // Helper function to build user ID filters
  const getUserIdsForFilters = async () => {
    if (!userType && !college && !department) {
      return null // No filtering needed
    }

    const userIds = new Set()

    // Build queries based on filters
    if (userType === 'student' || (!userType && (college || department))) {
      let query = supabase.from('registered_users').select('id')
      if (college) query = query.eq('college', college)
      if (department) query = query.eq('department', department)
      const { data } = await query
      if (data) data.forEach((u) => userIds.add(u.id))
    }

    if (userType === 'faculty' || (!userType && (college || department))) {
      let query = supabase.from('registered_faculty').select('id')
      if (college) query = query.eq('college', college)
      if (department) query = query.eq('department', department)
      const { data } = await query
      if (data) data.forEach((u) => userIds.add(u.id))
    }

    if (userType === 'visitor') {
      const { data } = await supabase
        .from('approved_visitors')
        .select('user_id')
        .eq('account_status', 'Active')
      if (data) data.forEach((u) => userIds.add(u.user_id))
    }

    return Array.from(userIds)
  }

  // Get filtered user IDs if filters are applied
  const filteredUserIds = await getUserIdsForFilters()

  // Generate charts first (this takes the longest) - pass filters to chart generation
  let chartImages = {}
  try {
    console.log('Generating charts...')
    chartImages = await renderReportCharts({
      startMonth,
      startDay,
      startYear,
      endMonth,
      endDay,
      endYear,
      userIds: filteredUserIds,
    })
    console.log('Charts generated successfully')
  } catch (error) {
    console.error('Failed to generate charts:', error)
    chartImages = {}
  }

  // Helper function to apply user ID filter to queries
  const applyUserFilter = (query) => {
    if (filteredUserIds && filteredUserIds.length > 0) {
      return query.in('id', filteredUserIds)
    }
    return query
  }

  // Supabase Queries
  const [
    totalUsersResult,
    newUsersResult,
    activeUsersResult,
    usersByTypeResult,
    departmentsResult,
    facultyDepartmentsResult,
    visitorDepartmentsResult,
    totalArtifactsResult,
    uploadedArtifactsResult,
    totalDocumentsResult,
    uploadedDocumentsResult,
    artifactLogsResult,
    documentLogsResult,
    appointmentLogsResult,
    totalAppointmentsResult,
  ] = await Promise.all([
    applyUserFilter(
      supabase
        .from('all_users')
        .select('*', { count: 'exact', head: true })
        .lte('created_at', endDate)
        .neq('user_type', 'admin'),
    ),
    applyUserFilter(
      supabase
        .from('all_users')
        .select('*', { count: 'exact', head: true })
        .gte('created_at', startDate)
        .lte('created_at', endDate)
        .neq('user_type', 'admin'),
    ),
    (() => {
      let query = supabase
        .from('logins')
        .select('user_id')
        .gte('login_at', startDate)
        .lte('login_at', endDate)
      if (filteredUserIds && filteredUserIds.length > 0) {
        query = query.in('user_id', filteredUserIds)
      }
      return query
    })(),
    applyUserFilter(
      supabase
        .from('all_users')
        .select('user_type')
        .gte('created_at', startDate)
        .lte('created_at', endDate)
        .neq('user_type', 'admin'),
    ),
    (() => {
      let query = supabase
        .from('registered_users')
        .select('department, college')
        .gte('created_at', startDate)
        .lte('created_at', endDate)
      if (college) query = query.eq('college', college)
      if (department) query = query.eq('department', department)
      return query
    })(),
    (() => {
      let query = supabase
        .from('registered_faculty')
        .select('department, college')
        .gte('created_at', startDate)
        .lte('created_at', endDate)
      if (college) query = query.eq('college', college)
      if (department) query = query.eq('department', department)
      return query
    })(),
    (() => {
      let query = supabase
        .from('registration_visitors')
        .select('institution')
        .gte('created_at', startDate)
        .lte('created_at', endDate)
        .eq('status', 'Approved')
      if (userType && userType !== 'visitor') {
        // If filtering by non-visitor type, return empty result
        return Promise.resolve({ data: [] })
      }
      return query
    })(),
    supabase
      .from('artifacts_metadata')
      .select('*', { count: 'exact', head: true })
      .lte('uploaded_at', endDate),
    supabase
      .from('artifacts_metadata')
      .select('*', { count: 'exact', head: true })
      .gte('uploaded_at', startDate)
      .lte('uploaded_at', endDate),
    supabase
      .from('documents_metadata')
      .select('*', { count: 'exact', head: true })
      .lte('uploaded_at', endDate),
    supabase
      .from('documents_metadata')
      .select('*', { count: 'exact', head: true })
      .gte('uploaded_at', startDate)
      .lte('uploaded_at', endDate),
    (() => {
      let query = supabase
        .from('user_activity_log')
        .select('item_id, user_id')
        .gte('clicked_at', startDate)
        .lte('clicked_at', endDate)
        .eq('item_type', 'artifact')
        .eq('action', 'view_artifact')
      if (filteredUserIds && filteredUserIds.length > 0) {
        query = query.in('user_id', filteredUserIds)
      }
      return query
    })(),
    (() => {
      let query = supabase
        .from('user_activity_log')
        .select('item_id, user_id')
        .gte('clicked_at', startDate)
        .lte('clicked_at', endDate)
        .eq('item_type', 'document')
        .eq('action', 'view_document')
      if (filteredUserIds && filteredUserIds.length > 0) {
        query = query.in('user_id', filteredUserIds)
      }
      return query
    })(),
    (() => {
      let query = supabase
        .from('appointment_booking')
        .select('*')
        .gte('created_at', startDate)
        .lte('created_at', endDate)
      if (filteredUserIds && filteredUserIds.length > 0) {
        query = query.in('user_id', filteredUserIds)
      }
      return query
    })(),
    (() => {
      let query = supabase
        .from('appointment_booking')
        .select('*', { count: 'exact', head: true })
        .lte('created_at', endDate)
      if (filteredUserIds && filteredUserIds.length > 0) {
        query = query.in('user_id', filteredUserIds)
      }
      return query
    })(),
  ])

  // Process results
  const totalUsers = totalUsersResult.count
  const newUsers = newUsersResult.count

  // Active users - validate that users still exist in the database and are not admins
  const loginUserIds = (activeUsersResult.data || []).map((r) => r.user_id)
  const uniqueLoginUserIds = [...new Set(loginUserIds)]

  // Query to check which users still exist and exclude admin/super admin
  const { data: existingUsers } = await supabase
    .from('all_users')
    .select('id, user_type')
    .in('id', uniqueLoginUserIds)
    .neq('user_type', 'admin')
    .neq('user_type', 'super admin')

  const existingUserIds = new Set((existingUsers || []).map((u) => u.id))
  const activeUsers = existingUserIds.size

  // User type statistics
  const userTypeCount = {}
  usersByTypeResult.data?.forEach((u) => {
    userTypeCount[u.user_type] = (userTypeCount[u.user_type] || 0) + 1
  })
  const userTypeStats = Object.entries(userTypeCount).map(([type, count]) => ({ type, count }))

  // Department statistics
  const deptCount = {}
  departmentsResult.data?.forEach((u) => {
    if (u.department) deptCount[u.department] = (deptCount[u.department] || 0) + 1
  })
  const departmentStats = Object.entries(deptCount).map(([name, users]) => ({ name, users }))

  const facultyDeptCount = {}
  facultyDepartmentsResult.data?.forEach((u) => {
    if (u.department) facultyDeptCount[u.department] = (facultyDeptCount[u.department] || 0) + 1
  })
  const facultyDepartmentStats = Object.entries(facultyDeptCount).map(([name, users]) => ({
    name,
    users,
  }))

  const visitorDeptCount = {}
  visitorDepartmentsResult.data?.forEach((u) => {
    if (u.institution) visitorDeptCount[u.institution] = (visitorDeptCount[u.institution] || 0) + 1
  })
  const institutionStats = Object.entries(visitorDeptCount).map(([name, users]) => ({
    name,
    users,
  }))

  const totalArtifacts = totalArtifactsResult.count
  const uploadedArtifacts = uploadedArtifactsResult.count
  const totalDocuments = totalDocumentsResult.count
  const uploadedDocuments = uploadedDocumentsResult.count

  // Get all admin and super admin user IDs to exclude from view counts
  const { data: adminUsers } = await supabase
    .from('all_users')
    .select('id')
    .in('user_type', ['admin', 'super admin'])

  const adminUserIds = new Set((adminUsers || []).map((a) => a.id))

  // Top artifacts and documents - only count views for items that still exist and exclude admin views
  // First, get all unique artifact and document IDs from the logs
  const artifactLogIds = [...new Set((artifactLogsResult.data || []).map((log) => log.item_id))]
  const documentLogIds = [...new Set((documentLogsResult.data || []).map((log) => log.item_id))]

  // Verify which artifacts and documents still exist in the database
  const [existingArtifactsResult, existingDocumentsResult] = await Promise.all([
    artifactLogIds.length > 0
      ? supabase.from('artifacts_metadata').select('id').in('id', artifactLogIds)
      : Promise.resolve({ data: [] }),
    documentLogIds.length > 0
      ? supabase.from('documents_metadata').select('id').in('id', documentLogIds)
      : Promise.resolve({ data: [] }),
  ])

  const existingArtifactIds = new Set((existingArtifactsResult.data || []).map((a) => a.id))
  const existingDocumentIds = new Set((existingDocumentsResult.data || []).map((d) => d.id))

  // Count views only for items that still exist and exclude admin/super admin views
  const artifactCount = {}
  artifactLogsResult.data?.forEach((log) => {
    if (existingArtifactIds.has(log.item_id) && !adminUserIds.has(log.user_id)) {
      artifactCount[log.item_id] = (artifactCount[log.item_id] || 0) + 1
    }
  })
  const sortedArtifacts = Object.entries(artifactCount)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10)

  const documentCount = {}
  documentLogsResult.data?.forEach((log) => {
    if (existingDocumentIds.has(log.item_id) && !adminUserIds.has(log.user_id)) {
      documentCount[log.item_id] = (documentCount[log.item_id] || 0) + 1
    }
  })
  const sortedDocuments = Object.entries(documentCount)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10)

  // Get metadata for top items
  const [artifactsMetaResult, documentsMetaResult] = await Promise.all([
    sortedArtifacts.length > 0
      ? supabase
          .from('artifacts_view')
          .select('item_id, title')
          .in(
            'item_id',
            sortedArtifacts.map(([id]) => id),
          )
      : Promise.resolve({ data: [] }),
    sortedDocuments.length > 0
      ? supabase
          .from('documents_view')
          .select('id, title')
          .in(
            'id',
            sortedDocuments.map(([id]) => id),
          )
      : Promise.resolve({ data: [] }),
  ])

  const topArtifacts = sortedArtifacts.map(([id, views]) => {
    const meta = artifactsMetaResult.data?.find((a) => a.item_id === id)
    return { name: meta?.title ?? `Artifact ${id}`, views }
  })

  const topDocuments = sortedDocuments.map(([id, views]) => {
    const meta = documentsMetaResult.data?.find((d) => d.id === id)
    return { name: meta?.title ?? `Document ${id}`, views }
  })

  // Process appointment statistics
  const totalAppointments = totalAppointmentsResult.count
  const newAppointments = appointmentLogsResult.data?.length || 0

  // Process appointment status statistics
  let appointmentPendingCount = 0
  let appointmentApprovedCount = 0
  let appointmentRejectedCount = 0
  appointmentLogsResult.data?.forEach((appointment) => {
    // Count by status
    const status = appointment.status || 'Pending'
    if (status === 'Approved') {
      appointmentApprovedCount += 1
    } else if (status === 'Rejected') {
      appointmentRejectedCount += 1
    } else {
      appointmentPendingCount += 1
    }
  })

  // Calculate comprehensive monthly breakdown
  const monthlyBreakdown = []
  const start = new Date(startYear, startMonth - 1, startDay)
  const end = new Date(endYear, endMonth - 1, endDay)

  // Get all data needed for monthly breakdown
  const [
    monthlyLoginsData,
    monthlyNewUsersData,
    monthlyArtifactsData,
    monthlyDocumentsData,
    monthlyAppointmentsData,
    monthlyArtifactViewsData,
    monthlyDocumentViewsData,
  ] = await Promise.all([
    supabase
      .from('logins')
      .select('user_id, login_at')
      .gte('login_at', startDate)
      .lte('login_at', endDate),
    supabase
      .from('all_users')
      .select('created_at, user_type')
      .gte('created_at', startDate)
      .lte('created_at', endDate)
      .neq('user_type', 'admin'),
    supabase
      .from('artifacts_metadata')
      .select('uploaded_at')
      .gte('uploaded_at', startDate)
      .lte('uploaded_at', endDate),
    supabase
      .from('documents_metadata')
      .select('uploaded_at')
      .gte('uploaded_at', startDate)
      .lte('uploaded_at', endDate),
    supabase
      .from('appointment_booking')
      .select('created_at, status')
      .gte('created_at', startDate)
      .lte('created_at', endDate),
    supabase
      .from('user_activity_log')
      .select('clicked_at, item_id, user_id')
      .gte('clicked_at', startDate)
      .lte('clicked_at', endDate)
      .eq('item_type', 'artifact')
      .eq('action', 'view_artifact'),
    supabase
      .from('user_activity_log')
      .select('clicked_at, item_id, user_id')
      .gte('clicked_at', startDate)
      .lte('clicked_at', endDate)
      .eq('item_type', 'document')
      .eq('action', 'view_document'),
  ])

  // Get admin user IDs to exclude from monthly view counts
  const { data: monthlyAdminUsers } = await supabase
    .from('all_users')
    .select('id')
    .in('user_type', ['admin', 'super admin'])

  const monthlyAdminUserIds = new Set((monthlyAdminUsers || []).map((a) => a.id))

  // Validate that users, artifacts, and documents still exist in the database
  // Exclude admin and super admin users from statistics
  const monthlyLoginUserIds = [...new Set((monthlyLoginsData.data || []).map((l) => l.user_id))]
  const monthlyArtifactIds = [
    ...new Set((monthlyArtifactViewsData.data || []).map((v) => v.item_id)),
  ]
  const monthlyDocumentIds = [
    ...new Set((monthlyDocumentViewsData.data || []).map((v) => v.item_id)),
  ]

  const [
    monthlyExistingUsersResult,
    monthlyExistingArtifactsResult,
    monthlyExistingDocumentsResult,
  ] = await Promise.all([
    monthlyLoginUserIds.length > 0
      ? supabase
          .from('all_users')
          .select('id, user_type')
          .in('id', monthlyLoginUserIds)
          .neq('user_type', 'admin')
          .neq('user_type', 'super admin')
      : Promise.resolve({ data: [] }),
    monthlyArtifactIds.length > 0
      ? supabase.from('artifacts_metadata').select('id').in('id', monthlyArtifactIds)
      : Promise.resolve({ data: [] }),
    monthlyDocumentIds.length > 0
      ? supabase.from('documents_metadata').select('id').in('id', monthlyDocumentIds)
      : Promise.resolve({ data: [] }),
  ])

  const monthlyExistingUserIds = new Set((monthlyExistingUsersResult.data || []).map((u) => u.id))
  const monthlyExistingArtifactIds = new Set(
    (monthlyExistingArtifactsResult.data || []).map((a) => a.id),
  )
  const monthlyExistingDocumentIds = new Set(
    (monthlyExistingDocumentsResult.data || []).map((d) => d.id),
  )

  // Check if all metrics are zero or empty
  const hasAnyData =
    totalUsers > 0 ||
    newUsers > 0 ||
    activeUsers > 0 ||
    totalAppointments > 0 ||
    newAppointments > 0 ||
    totalArtifacts > 0 ||
    uploadedArtifacts > 0 ||
    totalDocuments > 0 ||
    uploadedDocuments > 0 ||
    topArtifacts.length > 0 ||
    topDocuments.length > 0 ||
    departmentStats.length > 0 ||
    facultyDepartmentStats.length > 0 ||
    institutionStats.length > 0 ||
    userTypeStats.length > 0

  if (!hasAnyData) {
    return {
      success: false,
      noData: true,
      message: 'No data available for the selected date range',
    }
  }

  // Create monthly breakdown
  let currentMonth = new Date(start.getFullYear(), start.getMonth(), 1)
  const lastMonth = new Date(end.getFullYear(), end.getMonth(), 1)

  while (currentMonth <= lastMonth) {
    const monthStart = new Date(currentMonth.getFullYear(), currentMonth.getMonth(), 1)
    const monthEnd = new Date(
      currentMonth.getFullYear(),
      currentMonth.getMonth() + 1,
      0,
      23,
      59,
      59,
    )

    const monthName = monthStart.toLocaleString('default', { month: 'long', year: 'numeric' })

    // Active users this month (unique users who logged in and still exist in database)
    const monthLoginUserIds = (monthlyLoginsData.data || [])
      .filter((login) => {
        const loginDate = new Date(login.login_at)
        return loginDate >= monthStart && loginDate <= monthEnd
      })
      .map((login) => login.user_id)
      .filter((userId) => monthlyExistingUserIds.has(userId))

    const monthActiveUsers = new Set(monthLoginUserIds).size

    // New registrations this month by type
    const monthUsersData = (monthlyNewUsersData.data || []).filter((user) => {
      const regDate = new Date(user.created_at)
      return regDate >= monthStart && regDate <= monthEnd
    })

    const monthNewUsers = monthUsersData.length
    const monthNewStudents = monthUsersData.filter((u) => u.user_type === 'student').length
    const monthNewFaculty = monthUsersData.filter((u) => u.user_type === 'faculty').length
    const monthNewVisitors = monthUsersData.filter((u) => u.user_type === 'visitor').length

    // New artifacts this month
    const monthArtifacts = (monthlyArtifactsData.data || []).filter((artifact) => {
      const uploadDate = new Date(artifact.uploaded_at)
      return uploadDate >= monthStart && uploadDate <= monthEnd
    }).length

    // New documents this month
    const monthDocuments = (monthlyDocumentsData.data || []).filter((doc) => {
      const uploadDate = new Date(doc.uploaded_at)
      return uploadDate >= monthStart && uploadDate <= monthEnd
    }).length

    // Total uploads this month
    const monthUploads = monthArtifacts + monthDocuments

    // Appointments this month by status
    const monthAppointmentsData = (monthlyAppointmentsData.data || []).filter((apt) => {
      const aptDate = new Date(apt.created_at)
      return aptDate >= monthStart && aptDate <= monthEnd
    })

    const monthAppointments = monthAppointmentsData.length
    const monthAppointmentsPending = monthAppointmentsData.filter(
      (a) => a.status === 'Pending',
    ).length
    const monthAppointmentsApproved = monthAppointmentsData.filter(
      (a) => a.status === 'Approved',
    ).length
    const monthAppointmentsRejected = monthAppointmentsData.filter(
      (a) => a.status === 'Rejected',
    ).length

    // Content views this month - only count views for items that still exist and exclude admin views
    const monthArtifactViews = (monthlyArtifactViewsData.data || []).filter((view) => {
      const viewDate = new Date(view.clicked_at)
      return (
        viewDate >= monthStart &&
        viewDate <= monthEnd &&
        monthlyExistingArtifactIds.has(view.item_id) &&
        !monthlyAdminUserIds.has(view.user_id)
      )
    }).length

    const monthDocumentViews = (monthlyDocumentViewsData.data || []).filter((view) => {
      const viewDate = new Date(view.clicked_at)
      return (
        viewDate >= monthStart &&
        viewDate <= monthEnd &&
        monthlyExistingDocumentIds.has(view.item_id) &&
        !monthlyAdminUserIds.has(view.user_id)
      )
    }).length

    monthlyBreakdown.push({
      month: monthName,
      activeUsers: monthActiveUsers,
      newUsers: monthNewUsers,
      newStudents: monthNewStudents,
      newFaculty: monthNewFaculty,
      newVisitors: monthNewVisitors,
      totalUploads: monthUploads,
      artifacts: monthArtifacts,
      documents: monthDocuments,
      totalAppointments: monthAppointments,
      appointmentsPending: monthAppointmentsPending,
      appointmentsApproved: monthAppointmentsApproved,
      appointmentsRejected: monthAppointmentsRejected,
      artifactViews: monthArtifactViews,
      documentViews: monthDocumentViews,
      totalViews: monthArtifactViews + monthDocumentViews,
    })

    // Move to next month
    currentMonth.setMonth(currentMonth.getMonth() + 1)
  }

  // PDF Generation
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const TABLE_WIDTH = 150
  const centeredMargin = { left: (pageWidth - TABLE_WIDTH) / 2 }

  const tableOptions = {
    theme: 'grid',
    styles: { halign: 'center', valign: 'middle', fontSize: 11 },
    headStyles: { fillColor: [136, 0, 0], textColor: 255, halign: 'center' },
    columnStyles: { 0: { halign: 'left', cellWidth: 100 }, 1: { halign: 'center', cellWidth: 50 } },
    tableWidth: TABLE_WIDTH,
    margin: centeredMargin,
  }

  const tableOptions3Col = {
    ...tableOptions,
    columnStyles: { 0: { cellWidth: 50 }, 1: { cellWidth: 50 }, 2: { cellWidth: 50 } },
  }

  // Header
  let rangeText = ''
  const chartWidth = pageWidth - 50
  const center = (pageWidth - chartWidth) / 2
  const title = 'PRESERV3D Usage Report'

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.text(title, pageWidth / 2, 20, { align: 'center' })

  if (startMonth === endMonth && startDay === endDay && startYear === endYear) {
    rangeText = `${monthNames[startMonth - 1]} ${startDay}, ${startYear}`
  } else {
    rangeText = `${monthNames[startMonth - 1]} ${startDay}, ${startYear} to ${monthNames[endMonth - 1]} ${endDay}, ${endYear}`
  }

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.text(rangeText, pageWidth / 2, 27, { align: 'center' })
  let currentY = 40

  // User Overview Section
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.text('Users Overview', pageWidth / 2, currentY, { align: 'center' })
  currentY += 5

  // Summary table
  doc.setFontSize(12)
  autoTable(doc, {
    ...tableOptions3Col,
    startY: currentY,
    head: [['Total Users', 'New Users', 'Active Users']],
    body: [[totalUsers ?? 0, newUsers ?? 0, activeUsers ?? 0]],
  })
  currentY = doc.lastAutoTable.finalY + 7

  // Monthly Users Chart
  if (chartImages.monthlyUsers) {
    doc.addImage(chartImages.monthlyUsers, 'PNG', center, currentY, chartWidth, 80)
    currentY += 90
  }

  // User Types Chart
  if (chartImages.userTypes) {
    doc.addImage(chartImages.userTypes, 'PNG', center, currentY, pageWidth - 65, 70)
    currentY += 80
  }

  // User type stats table
  if (userTypeStats && userTypeStats.length > 0) {
    autoTable(doc, {
      ...tableOptions,
      startY: currentY,
      head: [['User Type', 'Count']],
      body: userTypeStats.map((u) => [u.type, u.count]),
    })
    currentY = doc.lastAutoTable.finalY + 10
  }

  // Comprehensive Monthly Breakdown Section
  if (monthlyBreakdown && monthlyBreakdown.length > 0) {
    // Add new page if needed
    if (currentY > 200) {
      doc.addPage()
      currentY = 25
    }

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(14)
    doc.text('Monthly Activity Breakdown', pageWidth / 2, currentY, { align: 'center' })
    currentY += 7

    // 1. User Activity Monthly Breakdown
    doc.setFontSize(12)
    doc.text('User Activity', pageWidth / 2, currentY, { align: 'center' })
    currentY += 3

    autoTable(doc, {
      theme: 'grid',
      styles: { halign: 'center', valign: 'middle', fontSize: 9 },
      headStyles: { fillColor: [136, 0, 0], textColor: 255, halign: 'center', fontStyle: 'bold' },
      columnStyles: {
        0: { halign: 'left', cellWidth: 40 },
        1: { halign: 'center', cellWidth: 22 },
        2: { halign: 'center', cellWidth: 22 },
        3: { halign: 'center', cellWidth: 22 },
        4: { halign: 'center', cellWidth: 22 },
        5: { halign: 'center', cellWidth: 22 },
      },
      margin: { left: (pageWidth - 150) / 2 },
      startY: currentY,
      head: [['Month', 'Active', 'New Users', 'Students', 'Faculty', 'Visitors']],
      body: monthlyBreakdown.map((m) => [
        m.month,
        m.activeUsers,
        m.newUsers,
        m.newStudents,
        m.newFaculty,
        m.newVisitors,
      ]),
    })
    currentY = doc.lastAutoTable.finalY + 10

    // 2. Content Upload Monthly Breakdown
    if (currentY > 220) {
      doc.addPage()
      currentY = 25
    }

    doc.setFontSize(12)
    doc.text('Content Uploads', pageWidth / 2, currentY, { align: 'center' })
    currentY += 3

    autoTable(doc, {
      theme: 'grid',
      styles: { halign: 'center', valign: 'middle', fontSize: 9 },
      headStyles: { fillColor: [136, 0, 0], textColor: 255, halign: 'center', fontStyle: 'bold' },
      columnStyles: {
        0: { halign: 'left', cellWidth: 60 },
        1: { halign: 'center', cellWidth: 30 },
        2: { halign: 'center', cellWidth: 30 },
        3: { halign: 'center', cellWidth: 30 },
      },
      margin: { left: (pageWidth - 150) / 2 },
      startY: currentY,
      head: [['Month', 'Total Uploads', 'Artifacts', 'Documents']],
      body: monthlyBreakdown.map((m) => [m.month, m.totalUploads, m.artifacts, m.documents]),
    })
    currentY = doc.lastAutoTable.finalY + 10

    // 3. Appointments Monthly Breakdown
    if (currentY > 220) {
      doc.addPage()
      currentY = 25
    }

    doc.setFontSize(12)
    doc.text('Appointments', pageWidth / 2, currentY, { align: 'center' })
    currentY += 3

    autoTable(doc, {
      theme: 'grid',
      styles: { halign: 'center', valign: 'middle', fontSize: 9 },
      headStyles: { fillColor: [136, 0, 0], textColor: 255, halign: 'center', fontStyle: 'bold' },
      columnStyles: {
        0: { halign: 'left', cellWidth: 50 },
        1: { halign: 'center', cellWidth: 25 },
        2: { halign: 'center', cellWidth: 25 },
        3: { halign: 'center', cellWidth: 25 },
        4: { halign: 'center', cellWidth: 25 },
      },
      margin: { left: (pageWidth - 150) / 2 },
      startY: currentY,
      head: [['Month', 'Total', 'Pending', 'Approved', 'Rejected']],
      body: monthlyBreakdown.map((m) => [
        m.month,
        m.totalAppointments,
        m.appointmentsPending,
        m.appointmentsApproved,
        m.appointmentsRejected,
      ]),
    })
    currentY = doc.lastAutoTable.finalY + 10

    // 4. Content Views Monthly Breakdown
    if (currentY > 220) {
      doc.addPage()
      currentY = 25
    }

    doc.setFontSize(12)
    doc.text('Content Views', pageWidth / 2, currentY, { align: 'center' })
    currentY += 3

    autoTable(doc, {
      theme: 'grid',
      styles: { halign: 'center', valign: 'middle', fontSize: 9 },
      headStyles: { fillColor: [136, 0, 0], textColor: 255, halign: 'center', fontStyle: 'bold' },
      columnStyles: {
        0: { halign: 'left', cellWidth: 60 },
        1: { halign: 'center', cellWidth: 30 },
        2: { halign: 'center', cellWidth: 30 },
        3: { halign: 'center', cellWidth: 30 },
      },
      margin: { left: (pageWidth - 150) / 2 },
      startY: currentY,
      head: [['Month', 'Total Views', 'Artifact Views', 'Document Views']],
      body: monthlyBreakdown.map((m) => [m.month, m.totalViews, m.artifactViews, m.documentViews]),
    })
    currentY = doc.lastAutoTable.finalY + 10
  }

  if (chartImages.totalAppointments || (newAppointments && newAppointments > 0)) {
    // New page
    doc.addPage()
    currentY = 25

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(14)
    doc.text('Appointments Overview', pageWidth / 2, currentY, { align: 'center' })
    currentY += 5

    // Monthly Appointments Chart
    if (chartImages.monthlyAppointments) {
      doc.addImage(chartImages.monthlyAppointments, 'PNG', center, currentY, chartWidth, 80)
      currentY += 90
    }

    // Appointment Status Chart
    if (chartImages.appointmentStatus) {
      doc.addImage(chartImages.appointmentStatus, 'PNG', center, currentY, chartWidth, 80)
      currentY += 90
    }

    // Appointments Table
    autoTable(doc, {
      ...tableOptions,
      startY: currentY,
      head: [['Appointments', 'Count']],
      body: [
        ['Overall', totalAppointments ?? 0],
        ['New', newAppointments ?? 0],
        ['Pending', appointmentPendingCount ?? 0],
        ['Approved', appointmentApprovedCount ?? 0],
        ['Rejected', appointmentRejectedCount ?? 0],
      ],
    })
  }

  // Departments Section
  if (chartImages.departments || (departmentStats && departmentStats.length > 0)) {
    // New Page
    doc.addPage()
    currentY = 25

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(14)
    doc.text('Departments Overview', pageWidth / 2, currentY, { align: 'center' })
    currentY += 10

    // Students by Department
    if (departmentStats && departmentStats.length > 0) {
      if (chartImages.studentDepartments) {
        doc.addImage(chartImages.studentDepartments, 'PNG', center, currentY, chartWidth, 80)
        currentY += 80
      }

      autoTable(doc, {
        ...tableOptions,
        startY: currentY + 5,
        head: [['Department', 'Students']],
        body: departmentStats.slice(0, 10).map((d) => [d.name, d.users]), // Limit to top 10
      })
      currentY = doc.lastAutoTable.finalY + 10
    }

    // Add new page if needed
    if (currentY > 200) {
      doc.addPage()
      currentY = 25
    }

    // Faculty by Department
    if (facultyDepartmentStats && facultyDepartmentStats.length > 0) {
      if (chartImages.facultyDepartments) {
        doc.addImage(chartImages.facultyDepartments, 'PNG', center, currentY, chartWidth, 80)
        currentY += 80
      }

      autoTable(doc, {
        ...tableOptions,
        startY: currentY + 5,
        head: [['Department', 'Faculty']],
        body: facultyDepartmentStats.slice(0, 10).map((d) => [d.name, d.users]),
      })
      currentY = doc.lastAutoTable.finalY + 10
    }

    // Add new page if needed
    if (currentY > 200) {
      doc.addPage()
      currentY = 25
    }

    // Visitors by Institution
    if (institutionStats && institutionStats.length > 0) {
      if (chartImages.visitorInstitutions) {
        doc.addImage(chartImages.visitorInstitutions, 'PNG', center, currentY, chartWidth, 80)
        currentY += 80
      }

      autoTable(doc, {
        ...tableOptions,
        startY: currentY + 5,
        head: [['Institution', 'Visitors']],
        body: institutionStats.slice(0, 10).map((i) => [i.name, i.users]),
      })
      currentY = doc.lastAutoTable.finalY + 10
    }
  }

  // Content Overview Section
  // Add new page
  doc.addPage()
  currentY = 30

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.text('Content Overview', pageWidth / 2, currentY, { align: 'center' })
  currentY += 5

  // Monthly Uploads Chart
  if (chartImages.monthlyUploads) {
    doc.addImage(chartImages.monthlyUploads, 'PNG', center, currentY, chartWidth, 80)
    currentY += 90
  }

  // Upload Distribution Chart
  if (chartImages.uploadComparison) {
    doc.addImage(chartImages.uploadComparison, 'PNG', center, currentY, chartWidth, 80)
    currentY += 90
  }

  // Content Summary Table
  autoTable(doc, {
    ...tableOptions3Col,
    columnStyles: {
      0: { halign: 'left', cellWidth: 80 },
      1: { halign: 'center', cellWidth: 35 },
      2: { halign: 'center', cellWidth: 35 },
    },
    startY: currentY,
    head: [['Content Type', 'New', 'Total']],
    body: [
      ['Artifacts', uploadedArtifacts ?? 0, totalArtifacts ?? 0],
      ['Documents', uploadedDocuments ?? 0, totalDocuments ?? 0],
    ],
  })
  currentY = doc.lastAutoTable.finalY + 10

  // Popular Content Section
  doc.addPage()
  currentY = 30
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.text('Popular Content', pageWidth / 2, currentY, { align: 'center' })
  currentY += 5

  // Top Artifacts Chart
  if (chartImages.topArtifacts) {
    doc.addImage(chartImages.topArtifacts, 'PNG', center, currentY, chartWidth, 80)
    currentY += 90
  }

  // Top Artifacts Table
  if (topArtifacts && topArtifacts.length > 0) {
    doc.setFontSize(12)
    // doc.text('Top Artifacts by Views', pageWidth / 2, currentY, { align: 'center' })
    autoTable(doc, {
      ...tableOptions,
      startY: currentY + 5,
      head: [['Artifact Name', 'Views']],
      body: topArtifacts.map((a) => [
        a.name.length > 40 ? a.name.substring(0, 40) + '...' : a.name,
        a.views,
      ]),
    })
    currentY = doc.lastAutoTable.finalY + 10
  }

  // New Page
  doc.addPage()
  currentY = 25

  // Top Documents Chart
  if (chartImages.topDocuments) {
    doc.addImage(chartImages.topDocuments, 'PNG', center, currentY, chartWidth, 80)
    currentY += 90
  }

  // Top Documents Table
  if (topDocuments && topDocuments.length > 0) {
    doc.setFontSize(12)
    // doc.text('Top Documents by Views', pageWidth / 2, currentY, { align: 'center' })
    autoTable(doc, {
      ...tableOptions,
      startY: currentY + 5,
      head: [['Document Name', 'Views']],
      body: topDocuments.map((d) => [
        d.name.length > 40 ? d.name.substring(0, 40) + '...' : d.name,
        d.views,
      ]),
    })
    currentY = doc.lastAutoTable.finalY + 10
  }

  // Final Summary Section
  // Add new page for summary
  doc.addPage()
  currentY = 30

  doc.setFontSize(16)
  doc.text('Summary Report', pageWidth / 2, currentY, { align: 'center' })
  currentY += 5

  // Key Metrics Summary
  autoTable(doc, {
    ...tableOptions,
    columnStyles: {
      0: { halign: 'left', cellWidth: 120 },
      1: { halign: 'center', cellWidth: 30 },
    },
    startY: currentY,
    head: [['Metric', 'Value']],
    body: [
      ['New Users (This Period)', newUsers ?? 0],
      ['New Appointments (This Period)', newAppointments ?? 0],
      ['New Artifacts (This Period)', uploadedArtifacts ?? 0],
      ['New Documents (This Period)', uploadedDocuments ?? 0],
      ['Active Users (This Period)', activeUsers ?? 0],
      ['Total Registered Users', totalUsers ?? 0],
      ['Total Appointments', totalAppointments ?? 0],
      ['Total Artifacts', totalArtifacts ?? 0],
      ['Total Documents', totalDocuments ?? 0],
      ['Student Users', userTypeCount.student ?? 0],
      ['Faculty Users', userTypeCount.faculty ?? 0],
      ['Visitor Users', userTypeCount.visitor ?? 0],
    ],
  })

  // Add Monthly Breakdown Summary
  if (monthlyBreakdown && monthlyBreakdown.length > 0) {
    currentY = doc.lastAutoTable.finalY + 15

    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text('Monthly Statistics Summary', pageWidth / 2, currentY, { align: 'center' })
    currentY += 5

    // Calculate totals and averages
    const totalActiveUsersAllMonths = monthlyBreakdown.reduce((sum, m) => sum + m.activeUsers, 0)
    const avgActiveUsersPerMonth = Math.round(totalActiveUsersAllMonths / monthlyBreakdown.length)
    const peakMonth = monthlyBreakdown.reduce((max, m) =>
      m.activeUsers > max.activeUsers ? m : max,
    )

    const totalNewUsersAllMonths = monthlyBreakdown.reduce((sum, m) => sum + m.newUsers, 0)
    const avgNewUsersPerMonth = Math.round(totalNewUsersAllMonths / monthlyBreakdown.length)

    const totalUploadsAllMonths = monthlyBreakdown.reduce((sum, m) => sum + m.totalUploads, 0)
    const avgUploadsPerMonth = Math.round(totalUploadsAllMonths / monthlyBreakdown.length)

    const totalAppointmentsAllMonths = monthlyBreakdown.reduce(
      (sum, m) => sum + m.totalAppointments,
      0,
    )
    const avgAppointmentsPerMonth = Math.round(totalAppointmentsAllMonths / monthlyBreakdown.length)

    const totalViewsAllMonths = monthlyBreakdown.reduce((sum, m) => sum + m.totalViews, 0)
    const avgViewsPerMonth = Math.round(totalViewsAllMonths / monthlyBreakdown.length)

    autoTable(doc, {
      ...tableOptions,
      columnStyles: {
        0: { halign: 'left', cellWidth: 100 },
        1: { halign: 'center', cellWidth: 50 },
      },
      startY: currentY,
      head: [['Metric', 'Value']],
      body: [
        ['Average Active Users per Month', avgActiveUsersPerMonth],
        ['Peak Activity Month', peakMonth.month],
        ['Peak Month Active Users', peakMonth.activeUsers],
        ['Average New Users per Month', avgNewUsersPerMonth],
        ['Average Uploads per Month', avgUploadsPerMonth],
        ['Average Appointments per Month', avgAppointmentsPerMonth],
        ['Average Content Views per Month', avgViewsPerMonth],
        ['Total Unique Active Users', activeUsers ?? 0],
      ],
    })
  }

  // Add footers to all pages
  const totalPages = doc.getNumberOfPages()
  const singleDate = startMonth === endMonth && startDay === endDay && startYear === endYear

  if (singleDate) {
    rangeText = `${monthNames[startMonth - 1]} ${startDay}, ${startYear}`
  } else {
    rangeText = `${monthNames[startMonth - 1]} ${startDay}, ${startYear} to ${monthNames[endMonth - 1]} ${endDay}, ${endYear}`
  }

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    addPageFooter(doc, i, totalPages, rangeText, user, { userType, college, department })
  }

  // Download Generated Report
  const filename = singleDate
    ? `PRESERV3D_UsageReport_${startYear}-${startMonth.toString().padStart(2, '0')}-${startDay.toString().padStart(2, '0')}.pdf`
    : `PRESERV3D_UsageReport_${startYear}-${startMonth.toString().padStart(2, '0')}-${startDay.toString().padStart(2, '0')}_to_${endYear}-${endMonth.toString().padStart(2, '0')}-${endDay.toString().padStart(2, '0')}.pdf`

  doc.save(filename)

  return {
    success: true,
    message: 'Report generated successfully',
    filename,
    metrics: {
      totalUsers,
      newUsers,
      activeUsers,
      totalAppointments,
      newAppointments,
      totalArtifacts,
      uploadedArtifacts,
      totalDocuments,
      uploadedDocuments,
      userTypeCount,
    },
  }
}
